/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    lat: number;
    lng: number;
    city: string;
}
export interface UserPreferences {
    incognito: boolean;
    notifyMatches: boolean;
    ageMax: bigint;
    ageMin: bigint;
    notifyLikes: boolean;
    notifyMessages: boolean;
    radiusKm: bigint;
}
export interface LikeEntry {
    isMatched: boolean;
    profile: UserProfile;
}
export interface QuizAnswers {
    answers: Array<bigint>;
    updatedAt: bigint;
}
export interface Message {
    id: bigint;
    text: string;
    sentAt: bigint;
    toPrincipal: Principal;
    fromPrincipal: Principal;
    readAt?: bigint;
}
export interface DiscoveryProfile {
    likedMe: boolean;
    distanceKm?: number;
    profile: UserProfile;
}
export interface Icebreaker {
    answer: string;
    prompt: string;
}
export interface ConversationSummary {
    lastMessage?: Message;
    withPrincipal: Principal;
    unreadCount: bigint;
    profile: UserProfile;
}
export interface UserProfile {
    bio: string;
    principal: Principal;
    interests: Array<string>;
    name: string;
    createdAt: bigint;
    icebreakers: Array<Icebreaker>;
    isVerified: boolean;
    genderPreference: Array<string>;
    birthday: bigint;
    gender: string;
    location?: Location;
    photos: Array<ExternalBlob>;
}
export interface backendInterface {
    blockUser(target: Principal): Promise<void>;
    deleteProfile(): Promise<void>;
    getBlockedUsers(): Promise<Array<Principal>>;
    getCompatibilityScore(target: Principal): Promise<bigint | null>;
    getConversations(): Promise<Array<ConversationSummary>>;
    getDiscovery(limit: bigint): Promise<Array<DiscoveryProfile>>;
    getFirstSharedAnswer(target: Principal): Promise<[bigint, bigint] | null>;
    getLikesReceived(): Promise<Array<LikeEntry>>;
    getLikesSent(): Promise<Array<LikeEntry>>;
    getMatchesCount(location: Location, radius: bigint): Promise<bigint>;
    getMessages(partner: Principal): Promise<Array<Message>>;
    getMyProfile(): Promise<UserProfile | null>;
    getMyQuizAnswers(): Promise<QuizAnswers | null>;
    getPreferences(): Promise<UserPreferences>;
    getPublicProfile(target: Principal): Promise<UserProfile | null>;
    markRead(partner: Principal): Promise<void>;
    reportUser(target: Principal, reason: string): Promise<void>;
    sendMessage(partner: Principal, text: string): Promise<bigint>;
    setPreferences(prefs: UserPreferences): Promise<void>;
    setProfile(name: string, birthday: bigint, bio: string, gender: string, genderPreference: Array<string>, interests: Array<string>, location: Location | null, icebreakers: Array<Icebreaker>, photos: Array<ExternalBlob>): Promise<void>;
    setQuizAnswers(answers: Array<bigint>): Promise<void>;
    swipe(target: Principal, action: string): Promise<boolean>;
    unblockUser(target: Principal): Promise<void>;
    unmatch(target: Principal): Promise<void>;
}
import type { ConversationSummary as _ConversationSummary, DiscoveryProfile as _DiscoveryProfile, ExternalBlob as _ExternalBlob, Icebreaker as _Icebreaker, LikeEntry as _LikeEntry, Location as _Location, Message as _Message, QuizAnswers as _QuizAnswers, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async blockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockUser(arg0);
            return result;
        }
    }
    async deleteProfile(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProfile();
            return result;
        }
    }
    async getBlockedUsers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlockedUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlockedUsers();
            return result;
        }
    }
    async getCompatibilityScore(arg0: Principal): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompatibilityScore(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompatibilityScore(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversations(): Promise<Array<ConversationSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversations();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversations();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDiscovery(arg0: bigint): Promise<Array<DiscoveryProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDiscovery(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDiscovery(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFirstSharedAnswer(arg0: Principal): Promise<[bigint, bigint] | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFirstSharedAnswer(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFirstSharedAnswer(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLikesReceived(): Promise<Array<LikeEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLikesReceived();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLikesReceived();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLikesSent(): Promise<Array<LikeEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLikesSent();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLikesSent();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatchesCount(arg0: Location, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchesCount(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchesCount(arg0, arg1);
            return result;
        }
    }
    async getMessages(arg0: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyQuizAnswers(): Promise<QuizAnswers | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyQuizAnswers();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyQuizAnswers();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPreferences(): Promise<UserPreferences> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreferences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreferences();
            return result;
        }
    }
    async getPublicProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicProfile(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicProfile(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async markRead(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markRead(arg0);
            return result;
        }
    }
    async reportUser(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportUser(arg0, arg1);
            return result;
        }
    }
    async sendMessage(arg0: Principal, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async setPreferences(arg0: UserPreferences): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPreferences(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPreferences(arg0);
            return result;
        }
    }
    async setProfile(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: Array<string>, arg5: Array<string>, arg6: Location | null, arg7: Array<Icebreaker>, arg8: Array<ExternalBlob>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProfile(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg6), arg7, await to_candid_vec_n26(this._uploadFile, this._downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProfile(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg6), arg7, await to_candid_vec_n26(this._uploadFile, this._downloadFile, arg8));
            return result;
        }
    }
    async setQuizAnswers(arg0: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setQuizAnswers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setQuizAnswers(arg0);
            return result;
        }
    }
    async swipe(arg0: Principal, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.swipe(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.swipe(arg0, arg1);
            return result;
        }
    }
    async unblockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockUser(arg0);
            return result;
        }
    }
    async unmatch(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unmatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unmatch(arg0);
            return result;
        }
    }
}
async function from_candid_ConversationSummary_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConversationSummary): Promise<ConversationSummary> {
    return await from_candid_record_n4(_uploadFile, _downloadFile, value);
}
async function from_candid_DiscoveryProfile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiscoveryProfile): Promise<DiscoveryProfile> {
    return await from_candid_record_n16(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_LikeEntry_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LikeEntry): Promise<LikeEntry> {
    return await from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Location]): Location | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [[bigint, bigint]]): [bigint, bigint] | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QuizAnswers]): QuizAnswers | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Message]): Message | null {
    return value.length === 0 ? null : from_candid_Message_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    principal: Principal;
    interests: Array<string>;
    name: string;
    createdAt: bigint;
    icebreakers: Array<_Icebreaker>;
    isVerified: boolean;
    genderPreference: Array<string>;
    birthday: bigint;
    gender: string;
    location: [] | [_Location];
    photos: Array<_ExternalBlob>;
}): Promise<{
    bio: string;
    principal: Principal;
    interests: Array<string>;
    name: string;
    createdAt: bigint;
    icebreakers: Array<Icebreaker>;
    isVerified: boolean;
    genderPreference: Array<string>;
    birthday: bigint;
    gender: string;
    location?: Location;
    photos: Array<ExternalBlob>;
}> {
    return {
        bio: value.bio,
        principal: value.principal,
        interests: value.interests,
        name: value.name,
        createdAt: value.createdAt,
        icebreakers: value.icebreakers,
        isVerified: value.isVerified,
        genderPreference: value.genderPreference,
        birthday: value.birthday,
        gender: value.gender,
        location: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.location)),
        photos: await from_candid_vec_n12(_uploadFile, _downloadFile, value.photos)
    };
}
async function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    likedMe: boolean;
    distanceKm: [] | [number];
    profile: _UserProfile;
}): Promise<{
    likedMe: boolean;
    distanceKm?: number;
    profile: UserProfile;
}> {
    return {
        likedMe: value.likedMe,
        distanceKm: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.distanceKm)),
        profile: await from_candid_UserProfile_n9(_uploadFile, _downloadFile, value.profile)
    };
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isMatched: boolean;
    profile: _UserProfile;
}): Promise<{
    isMatched: boolean;
    profile: UserProfile;
}> {
    return {
        isMatched: value.isMatched,
        profile: await from_candid_UserProfile_n9(_uploadFile, _downloadFile, value.profile)
    };
}
async function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastMessage: [] | [_Message];
    withPrincipal: Principal;
    unreadCount: bigint;
    profile: _UserProfile;
}): Promise<{
    lastMessage?: Message;
    withPrincipal: Principal;
    unreadCount: bigint;
    profile: UserProfile;
}> {
    return {
        lastMessage: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.lastMessage)),
        withPrincipal: value.withPrincipal,
        unreadCount: value.unreadCount,
        profile: await from_candid_UserProfile_n9(_uploadFile, _downloadFile, value.profile)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    text: string;
    sentAt: bigint;
    toPrincipal: Principal;
    fromPrincipal: Principal;
    readAt: [] | [bigint];
}): {
    id: bigint;
    text: string;
    sentAt: bigint;
    toPrincipal: Principal;
    fromPrincipal: Principal;
    readAt?: bigint;
} {
    return {
        id: value.id,
        text: value.text,
        sentAt: value.sentAt,
        toPrincipal: value.toPrincipal,
        fromPrincipal: value.fromPrincipal,
        readAt: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.readAt))
    };
}
async function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n13(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DiscoveryProfile>): Promise<Array<DiscoveryProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_DiscoveryProfile_n15(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LikeEntry>): Promise<Array<LikeEntry>> {
    return await Promise.all(value.map(async (x)=>await from_candid_LikeEntry_n20(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConversationSummary>): Promise<Array<ConversationSummary>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ConversationSummary_n3(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n6(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Location | null): [] | [_Location] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n27(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
