/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Message = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'sentAt' : IDL.Int,
  'toPrincipal' : IDL.Principal,
  'fromPrincipal' : IDL.Principal,
  'readAt' : IDL.Opt(IDL.Int),
});
export const Icebreaker = IDL.Record({
  'answer' : IDL.Text,
  'prompt' : IDL.Text,
});
export const Location = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'city' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'principal' : IDL.Principal,
  'interests' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'icebreakers' : IDL.Vec(Icebreaker),
  'isVerified' : IDL.Bool,
  'genderPreference' : IDL.Vec(IDL.Text),
  'birthday' : IDL.Int,
  'gender' : IDL.Text,
  'location' : IDL.Opt(Location),
  'photos' : IDL.Vec(ExternalBlob),
});
export const ConversationSummary = IDL.Record({
  'lastMessage' : IDL.Opt(Message),
  'withPrincipal' : IDL.Principal,
  'unreadCount' : IDL.Nat,
  'profile' : UserProfile,
});
export const DiscoveryProfile = IDL.Record({
  'likedMe' : IDL.Bool,
  'distanceKm' : IDL.Opt(IDL.Float64),
  'profile' : UserProfile,
});
export const LikeEntry = IDL.Record({
  'isMatched' : IDL.Bool,
  'profile' : UserProfile,
});
export const QuizAnswers = IDL.Record({
  'answers' : IDL.Vec(IDL.Nat),
  'updatedAt' : IDL.Int,
});
export const UserPreferences = IDL.Record({
  'incognito' : IDL.Bool,
  'notifyMatches' : IDL.Bool,
  'ageMax' : IDL.Nat,
  'ageMin' : IDL.Nat,
  'notifyLikes' : IDL.Bool,
  'notifyMessages' : IDL.Bool,
  'radiusKm' : IDL.Nat,
});

export const idlService = IDL.Service({
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'deleteProfile' : IDL.Func([], [], []),
  'getBlockedUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getCompatibilityScore' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Nat)],
      ['query'],
    ),
  'getConversations' : IDL.Func([], [IDL.Vec(ConversationSummary)], ['query']),
  'getDiscovery' : IDL.Func([IDL.Nat], [IDL.Vec(DiscoveryProfile)], ['query']),
  'getFirstSharedAnswer' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Tuple(IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getLikesReceived' : IDL.Func([], [IDL.Vec(LikeEntry)], ['query']),
  'getLikesSent' : IDL.Func([], [IDL.Vec(LikeEntry)], ['query']),
  'getMatchesCount' : IDL.Func([Location, IDL.Nat], [IDL.Nat], ['query']),
  'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMyQuizAnswers' : IDL.Func([], [IDL.Opt(QuizAnswers)], ['query']),
  'getPreferences' : IDL.Func([], [UserPreferences], ['query']),
  'getPublicProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'markRead' : IDL.Func([IDL.Principal], [], []),
  'reportUser' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
  'setPreferences' : IDL.Func([UserPreferences], [], []),
  'setProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Opt(Location),
        IDL.Vec(Icebreaker),
        IDL.Vec(ExternalBlob),
      ],
      [],
      [],
    ),
  'setQuizAnswers' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
  'swipe' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], []),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
  'unmatch' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'sentAt' : IDL.Int,
    'toPrincipal' : IDL.Principal,
    'fromPrincipal' : IDL.Principal,
    'readAt' : IDL.Opt(IDL.Int),
  });
  const Icebreaker = IDL.Record({ 'answer' : IDL.Text, 'prompt' : IDL.Text });
  const Location = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'city' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'principal' : IDL.Principal,
    'interests' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'icebreakers' : IDL.Vec(Icebreaker),
    'isVerified' : IDL.Bool,
    'genderPreference' : IDL.Vec(IDL.Text),
    'birthday' : IDL.Int,
    'gender' : IDL.Text,
    'location' : IDL.Opt(Location),
    'photos' : IDL.Vec(ExternalBlob),
  });
  const ConversationSummary = IDL.Record({
    'lastMessage' : IDL.Opt(Message),
    'withPrincipal' : IDL.Principal,
    'unreadCount' : IDL.Nat,
    'profile' : UserProfile,
  });
  const DiscoveryProfile = IDL.Record({
    'likedMe' : IDL.Bool,
    'distanceKm' : IDL.Opt(IDL.Float64),
    'profile' : UserProfile,
  });
  const LikeEntry = IDL.Record({
    'isMatched' : IDL.Bool,
    'profile' : UserProfile,
  });
  const QuizAnswers = IDL.Record({
    'answers' : IDL.Vec(IDL.Nat),
    'updatedAt' : IDL.Int,
  });
  const UserPreferences = IDL.Record({
    'incognito' : IDL.Bool,
    'notifyMatches' : IDL.Bool,
    'ageMax' : IDL.Nat,
    'ageMin' : IDL.Nat,
    'notifyLikes' : IDL.Bool,
    'notifyMessages' : IDL.Bool,
    'radiusKm' : IDL.Nat,
  });
  
  return IDL.Service({
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'deleteProfile' : IDL.Func([], [], []),
    'getBlockedUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getCompatibilityScore' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'getConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'getDiscovery' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(DiscoveryProfile)],
        ['query'],
      ),
    'getFirstSharedAnswer' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Tuple(IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getLikesReceived' : IDL.Func([], [IDL.Vec(LikeEntry)], ['query']),
    'getLikesSent' : IDL.Func([], [IDL.Vec(LikeEntry)], ['query']),
    'getMatchesCount' : IDL.Func([Location, IDL.Nat], [IDL.Nat], ['query']),
    'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMyQuizAnswers' : IDL.Func([], [IDL.Opt(QuizAnswers)], ['query']),
    'getPreferences' : IDL.Func([], [UserPreferences], ['query']),
    'getPublicProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'markRead' : IDL.Func([IDL.Principal], [], []),
    'reportUser' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
    'setPreferences' : IDL.Func([UserPreferences], [], []),
    'setProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Opt(Location),
          IDL.Vec(Icebreaker),
          IDL.Vec(ExternalBlob),
        ],
        [],
        [],
      ),
    'setQuizAnswers' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
    'swipe' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], []),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
    'unmatch' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };