/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ConversationSummary {
  'lastMessage' : [] | [Message],
  'withPrincipal' : Principal,
  'unreadCount' : bigint,
  'profile' : UserProfile,
}
export interface DiscoveryProfile {
  'likedMe' : boolean,
  'distanceKm' : [] | [number],
  'profile' : UserProfile,
}
export type ExternalBlob = Uint8Array;
export interface Icebreaker { 'answer' : string, 'prompt' : string }
export interface LikeEntry { 'isMatched' : boolean, 'profile' : UserProfile }
export interface Location { 'lat' : number, 'lng' : number, 'city' : string }
export interface Message {
  'id' : bigint,
  'text' : string,
  'sentAt' : bigint,
  'toPrincipal' : Principal,
  'fromPrincipal' : Principal,
  'readAt' : [] | [bigint],
}
export interface QuizAnswers { 'answers' : Array<bigint>, 'updatedAt' : bigint }
export interface UserPreferences {
  'incognito' : boolean,
  'notifyMatches' : boolean,
  'ageMax' : bigint,
  'ageMin' : bigint,
  'notifyLikes' : boolean,
  'notifyMessages' : boolean,
  'radiusKm' : bigint,
}
export interface UserProfile {
  'bio' : string,
  'principal' : Principal,
  'interests' : Array<string>,
  'name' : string,
  'createdAt' : bigint,
  'icebreakers' : Array<Icebreaker>,
  'isVerified' : boolean,
  'genderPreference' : Array<string>,
  'birthday' : bigint,
  'gender' : string,
  'location' : [] | [Location],
  'photos' : Array<ExternalBlob>,
}
export interface _SERVICE {
  'blockUser' : ActorMethod<[Principal], undefined>,
  'deleteProfile' : ActorMethod<[], undefined>,
  'getBlockedUsers' : ActorMethod<[], Array<Principal>>,
  'getCompatibilityScore' : ActorMethod<[Principal], [] | [bigint]>,
  'getConversations' : ActorMethod<[], Array<ConversationSummary>>,
  'getDiscovery' : ActorMethod<[bigint], Array<DiscoveryProfile>>,
  'getFirstSharedAnswer' : ActorMethod<[Principal], [] | [[bigint, bigint]]>,
  'getLikesReceived' : ActorMethod<[], Array<LikeEntry>>,
  'getLikesSent' : ActorMethod<[], Array<LikeEntry>>,
  'getMatchesCount' : ActorMethod<[Location, bigint], bigint>,
  'getMessages' : ActorMethod<[Principal], Array<Message>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMyQuizAnswers' : ActorMethod<[], [] | [QuizAnswers]>,
  'getPreferences' : ActorMethod<[], UserPreferences>,
  'getPublicProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'markRead' : ActorMethod<[Principal], undefined>,
  'reportUser' : ActorMethod<[Principal, string], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], bigint>,
  'setPreferences' : ActorMethod<[UserPreferences], undefined>,
  'setProfile' : ActorMethod<
    [
      string,
      bigint,
      string,
      string,
      Array<string>,
      Array<string>,
      [] | [Location],
      Array<Icebreaker>,
      Array<ExternalBlob>,
    ],
    undefined
  >,
  'setQuizAnswers' : ActorMethod<[Array<bigint>], undefined>,
  'swipe' : ActorMethod<[Principal, string], boolean>,
  'unblockUser' : ActorMethod<[Principal], undefined>,
  'unmatch' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];